doctrine_migrations:
    storage:
        table_storage:
            table_name: migration_versions

    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'

    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Migrations\Factory\MigrationFactoryDecorator'
