parameters:
    env(APP_DEFAULT_LOCALE): 'fr'

framework:
    default_locale: '%env(string:APP_DEFAULT_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
