twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        #- 'bootstrap_4_layout.html.twig'
        - 'bootstrap_4_horizontal_layout.html.twig'
        - '_form/custom_types.html.twig'
    globals:
        html_class: '@App\Twig\Variable\HtmlClass'
