variables:
  CONTAINER_RELEASE_IMAGE: "nanawel/reciphpes"

stages:
  - check
  - build
  - release

before_script:
  - time docker info

build_image:
  stage: build
  script:
    - time make build

push_image_latest:
  stage: release
  script:
    - time docker tag reciphpes:${WEBAPP_VERSION:-latest} ${CONTAINER_RELEASE_IMAGE}:latest
    - time docker push ${CONTAINER_RELEASE_IMAGE}:latest

push_image_tagged:
  stage: release
  script:
    - time docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_REF_SLUG}
  only:
    - /^\d+\.\d+\.\d+.*
