variables:
  CONTAINER_RELEASE_IMAGE: "nanawel/reciphpes"

stages:
  - check
  - build
  - release

before_script:
  - docker info

build_image:
  stage: build
  script:
    - make build

push_image_latest:
  stage: release
  script:
    - docker push ${CONTAINER_RELEASE_IMAGE}:latest

push_image_tagged:
  stage: release
  script:
    - docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_REF_SLUG}
  only:
    - /^\d+\.\d+\.\d+.*
