# Reciphpes - Prod Image

version: '3.2'

services:
  app:
    image: 'reciphpes:${WEBAPP_VERSION:-latest}'
    build:
      dockerfile: './docker/prod/Dockerfile'
      context: './'
    ports:
      - '${HTTP_PORT:-80}:80'
    volumes:
      - db:/var/www/webapp/var/db:rw
      - logs:/var/www/webapp/var/log:rw
      # Uncomment this to mount your own .env.local file
      #- './data/env:/var/www/webapp/.env.local:ro'

volumes:
  db:
  logs:
