index:
  path: /
  controller: App\Controller\HomeController::index

### RECIPE
app_recipe:
  path: /recipe
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /recipe/grid
    permanent: true

app_recipe_grid:
  path: /recipe/grid
  controller: App\Controller\RecipeController::grid

app_recipe_show:
  path: /recipe/show/{id}
  controller: App\Controller\RecipeController::show

app_recipe_new:
  path: /recipe/edit
  controller: App\Controller\RecipeController::edit

app_recipe_edit:
  path: /recipe/edit/{id}
  controller: App\Controller\RecipeController::edit

app_recipe_delete:
  path: /recipe/delete/{id}
  controller: App\Controller\RecipeController::delete

app_recipe_masscreate:
  path: /recipe/massCreate
  controller: App\Controller\RecipeController::massCreate

app_recipe_tag_search:
  path: /recipe_tags/search
  controller: App\Controller\RecipeController::searchTags

### INGREDIENT
app_ingredient:
  path: /ingredient
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /ingredient/grid
    permanent: true

app_ingredient_grid:
  path: /ingredient/grid
  controller: App\Controller\IngredientController::grid

app_ingredient_show:
  path: /ingredient/show/{id}
  controller: App\Controller\IngredientController::show

app_ingredient_new:
  path: /ingredient/edit
  controller: App\Controller\IngredientController::edit

app_ingredient_edit:
  path: /ingredient/edit/{id}
  controller: App\Controller\IngredientController::edit

app_ingredient_delete:
  path: /ingredient/delete/{id}
  controller: App\Controller\IngredientController::delete

app_ingredient_search:
  path: /ingredients/search
  controller: App\Controller\IngredientController::search

### LOCATION
app_location:
  path: /location
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /location/grid
    permanent: true

app_location_grid:
  path: /location/grid
  controller: App\Controller\LocationController::grid

app_location_show:
  path: /location/show/{id}
  controller: App\Controller\LocationController::show

app_location_new:
  path: /location/edit
  controller: App\Controller\LocationController::edit

app_location_edit:
  path: /location/edit/{id}
  controller: App\Controller\LocationController::edit

app_location_delete:
  path: /location/delete/{id}
  controller: App\Controller\LocationController::delete

### TAG
app_tag:
  path: /tag
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tag/grid
    permanent: true

app_tag_grid:
  path: /tag/grid
  controller: App\Controller\TagController::grid

app_tag_show:
  path: /tag/show/{id}
  controller: App\Controller\TagController::show

app_tag_new:
  path: /tag/edit
  controller: App\Controller\TagController::edit

app_tag_edit:
  path: /tag/edit/{id}
  controller: App\Controller\TagController::edit

app_tag_delete:
  path: /tag/delete/{id}
  controller: App\Controller\TagController::delete

### SEARCH
app_search_results:
  path: /search/results
  controller: App\Controller\SearchController::results
