#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\HomeController::index

app_index_index:
  path: /
  controller: App\Controller\HomeController::index

### RECIPE
app_recipe:
  path: /recipe
  controller: App\Controller\RecipeController::index

app_recipe_grid:
  path: /recipe/grid
  controller: App\Controller\RecipeController::grid

app_recipe_show:
  path: /recipe/show/{id}
  controller: App\Controller\RecipeController::show

app_recipe_new:
  path: /recipe/edit
  controller: App\Controller\RecipeController::edit

app_recipe_edit:
  path: /recipe/edit/{id}
  controller: App\Controller\RecipeController::edit

app_recipe_delete:
  path: /recipe/delete/{id}
  controller: App\Controller\RecipeController::delete

### LOCATION
app_location:
  path: /location
  controller: App\Controller\LocationController::index

app_location_grid:
  path: /location/grid
  controller: App\Controller\LocationController::grid

app_location_edit:
  path: /location/edit
  controller: App\Controller\LocationController::edit

app_location_delete:
  path: /location/delete/{id}
  controller: App\Controller\LocationController::delete

### INGREDIENT
app_ingredient:
  path: /ingredient
  controller: App\Controller\IngredientController::index

app_ingredient_grid:
  path: /ingredient/grid
  controller: App\Controller\IngredientController::grid

app_ingredient_edit:
  path: /ingredient/edit
  controller: App\Controller\IngredientController::edit

app_ingredient_delete:
  path: /ingredient/delete/{id}
  controller: App\Controller\IngredientController::delete

### SEARCH
search_results:
  path: /search/results
  controller: App\Controller\SearchController::results
