# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    App\EventListener\EnableForeignKeysOnDelete:
        tags:
            - name: doctrine.event_subscriber
              connection: default

    App\Service\AccessManager:
        class: ~
        arguments:
            $session: '@session'
            $writeAccessPassword: '%env(RECIPHPES_PASSWORD)%'

    ### MODELS
    App\Entity\Registry:
        class: App\Entity\Registry
        arguments:
            $entityConfigurations:
                recipe:
                    class: App\Entity\Recipe
                    form_class: App\Form\Recipe
                    type: recipe
                    route_prefix: recipe
                    template_prefix: recipe
                    import_class: App\Import\Recipe
                    datatable_type_class: App\DataTable\Type\Recipe
                ingredient:
                    class: App\Entity\Ingredient
                    form_class: App\Form\Ingredient
                    type: ingredient
                    route_prefix: ingredient
                    template_prefix: ingredient
                    datatable_type_class: App\DataTable\Type\Ingredient
                location:
                    class: App\Entity\Location
                    form_class: App\Form\Location
                    type: location
                    route_prefix: location
                    template_prefix: location
                    datatable_type_class: App\DataTable\Type\Location
                tag:
                    class: App\Entity\Tag
                    form_class: App\Form\Tag
                    type: tag
                    route_prefix: tag
                    template_prefix: tag
                    datatable_type_class: App\DataTable\Type\Tag

    ### COMMANDS
    App\Command\Import\Entities:
        class: ~
        tags: ['console.command']

    ### IMPORT
    App\Import\Recipe:
        public: true
